# Generated by Django 4.2.21 on 2025-05-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='destinations/')),
                ('subdestinations', models.TextField(blank=True, help_text='Comma-separated list (e.g. Borrowdale, Avondale)')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('map_link', models.URLField(blank=True, help_text='Optional Google Maps link')),
            ],
        ),
    ]
