# Generated by Django 4.2.21 on 2025-05-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='map_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='subdestinations',
            field=models.TextField(blank=True),
        ),
    ]
