# Generated by Django 4.2.21 on 2025-06-17 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_company_address_user_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wallet_balance',
        ),
    ]
