# Generated by Django 4.2.21 on 2025-07-18 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/birth_certificates/'),
        ),
        migrations.AddField(
            model_name='user',
            name='certificate_of_incorporation',
            field=models.FileField(blank=True, null=True, upload_to='documents/incorporation/'),
        ),
        migrations.AddField(
            model_name='user',
            name='corporate_tax_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/corporate_tax/'),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.CharField(blank=True, choices=[('Falcon', 'Falcon'), ('St George', 'St George'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vat_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/vat_certificates/'),
        ),
    ]
