# Generated by Django 4.2.21 on 2025-07-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_age_user_birth_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approval_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('corporate', 'Corporate'), ('student', 'Student')], default='individual', max_length=10),
        ),
    ]
