# Generated by Django 4.2.21 on 2025-07-29 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_approval_comment_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='club_card_bank',
            field=models.CharField(blank=True, choices=[('BANCABC', 'BANCABC'), ('CBZ', 'CBZ')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='club_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='number_of_members',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('corporate', 'Corporate'), ('student', 'Student'), ('club', 'Club')], default='individual', max_length=10),
        ),
    ]
