# Generated by Django 4.2.21 on 2025-08-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_password_reset_code_user_password_reset_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='welcome_points_awarded',
            field=models.BooleanField(default=False),
        ),
    ]
