# Generated by Django 5.2.6 on 2025-12-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_welcome_points_awarded'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('password_hash', models.CharField(max_length=255)),
                ('user_type', models.CharField(choices=[('individual', 'Individual'), ('corporate', 'Corporate'), ('student', 'Student'), ('club', 'Club')], default='individual', max_length=20)),
                ('email_verification_code', models.CharField(max_length=6)),
                ('verification_code_expires', models.DateTimeField()),
                ('verification_attempts', models.IntegerField(default=0)),
                ('last_verification_attempt', models.DateTimeField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('company_registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('tin_tax_number', models.CharField(blank=True, max_length=100, null=True)),
                ('vat_certificate', models.FileField(blank=True, null=True, upload_to='documents/pending/vat_certificates/')),
                ('corporate_tax_document', models.FileField(blank=True, null=True, upload_to='documents/pending/corporate_tax/')),
                ('certificate_of_incorporation', models.FileField(blank=True, null=True, upload_to='documents/pending/incorporation/')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('institution', models.CharField(blank=True, choices=[('Falcon', 'Falcon'), ('St George', 'St George'), ('Other', 'Other')], max_length=50, null=True)),
                ('custom_institution', models.CharField(blank=True, max_length=200, null=True)),
                ('student_id', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to='documents/pending/birth_certificates/')),
                ('club_name', models.CharField(blank=True, max_length=200, null=True)),
                ('number_of_members', models.PositiveIntegerField(blank=True, null=True)),
                ('club_card_bank', models.CharField(blank=True, choices=[('BANCABC', 'BANCABC'), ('CBZ', 'CBZ')], max_length=20, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='users_pendi_email_97312b_idx'), models.Index(fields=['phone_number'], name='users_pendi_phone_n_fc538d_idx'), models.Index(fields=['email_verification_code'], name='users_pendi_email_v_d7ea95_idx')],
            },
        ),
    ]
