# Generated by Django 4.2.21 on 2025-05-20 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0002_alter_destination_map_link_alter_destination_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_threshold', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_time', models.CharField(max_length=100)),
                ('distance', models.CharField(max_length=100)),
                ('from_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='destinations.destination')),
                ('to_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='destinations.destination')),
            ],
        ),
    ]
