# Generated by Django 4.2.21 on 2025-05-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('ZAR', 'ZAR')], default='USD', max_length=3),
        ),
    ]
