# Generated by Django 4.2.21 on 2025-07-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_installment_amount_booking_installment_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('laybuy', 'Laybuy'), ('under_payment', 'Under Payment')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookinghistory',
            name='status_from',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('laybuy', 'Laybuy'), ('under_payment', 'Under Payment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bookinghistory',
            name='status_to',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('laybuy', 'Laybuy'), ('under_payment', 'Under Payment')], max_length=20),
        ),
    ]
