# Generated by Django 5.2.6 on 2025-10-16 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_processedtransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoCashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency_code', models.CharField(max_length=5)),
                ('client_correlator', models.CharField(db_index=True, max_length=255, unique=True)),
                ('reference_code', models.CharField(db_index=True, max_length=255)),
                ('server_reference_code', models.CharField(blank=True, max_length=255, null=True)),
                ('ecocash_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('end_user_id', models.CharField(max_length=20)),
                ('transaction_type', models.CharField(choices=[('MER', 'Merchant Payment'), ('REF', 'Refund')], default='MER', max_length=5)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending_subscriber', 'Pending Subscriber Validation'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='initiated', max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('original_ecocash_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('notify_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_request', models.JSONField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wallets_ecocashtransaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='processedtransaction',
            name='wallets_pro_transac_3c11c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='processedtransaction',
            name='wallets_pro_created_3fbae7_idx',
        ),
        migrations.AddField(
            model_name='ecocashtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ecocashtransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecocash_transactions', to='wallets.wallet'),
        ),
    ]
