# Generated by Django 5.2.6 on 2025-10-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_ecocashtransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecocashtransaction',
            name='timeout_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
