# Generated by Django 5.2.6 on 2025-12-04 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
        ('wallets', '0005_add_timeout_to_ecocash_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processedtransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='processedtransaction',
            name='bancabc_reference',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processedtransaction',
            name='branch_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processedtransaction',
            name='customer_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processedtransaction',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processedtransaction',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processedtransaction',
            name='operator_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processedtransaction',
            name='payment_channel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='processedtransaction',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processedtransaction',
            name='payment_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processedtransaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('branch', 'Branch'), ('digital', 'Digital Banking'), ('kiosk', 'Kiosk'), ('agent', 'Agent'), ('mobile_app', 'Mobile App'), ('internet_banking', 'Internet Banking')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='processedtransaction',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='processedtransaction',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='processedtransaction',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='processedtransaction',
            index=models.Index(fields=['bancabc_reference'], name='wallets_pro_bancabc_2575e9_idx'),
        ),
        migrations.AddIndex(
            model_name='processedtransaction',
            index=models.Index(fields=['payment_status'], name='wallets_pro_payment_b86fde_idx'),
        ),
        migrations.AddIndex(
            model_name='processedtransaction',
            index=models.Index(fields=['payment_verified'], name='wallets_pro_payment_9dcd13_idx'),
        ),
        migrations.AddIndex(
            model_name='processedtransaction',
            index=models.Index(fields=['created_at'], name='wallets_pro_created_3fbae7_idx'),
        ),
        migrations.AddIndex(
            model_name='processedtransaction',
            index=models.Index(fields=['branch_code'], name='wallets_pro_branch__037149_idx'),
        ),
    ]
