# Generated by Django 5.2.6 on 2025-12-07 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0006_alter_processedtransaction_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedtransaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BancABCAPILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(choices=[('wallet_validate', 'Wallet Validation'), ('payment_notify', 'Payment Notification'), ('wallet_credit', 'Wallet Credit (Credit Push)'), ('transaction_report', 'Transaction Report'), ('other', 'Other')], max_length=50)),
                ('request_method', models.CharField(default='POST', max_length=10)),
                ('request_url', models.CharField(max_length=500)),
                ('request_headers', models.JSONField(blank=True, null=True)),
                ('request_body', models.JSONField(blank=True, null=True)),
                ('response_status_code', models.IntegerField()),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('error', 'Error'), ('validation_error', 'Validation Error'), ('auth_error', 'Authentication Error')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_id', models.IntegerField(blank=True, null=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('auto_credited', models.BooleanField(default=False)),
                ('credit_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'BancABC API Log',
                'verbose_name_plural': 'BancABC API Logs',
                'db_table': 'wallets_bancabc_api_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['endpoint'], name='wallets_ban_endpoin_6293f8_idx'), models.Index(fields=['status'], name='wallets_ban_status_178023_idx'), models.Index(fields=['created_at'], name='wallets_ban_created_285da5_idx'), models.Index(fields=['phone_number'], name='wallets_ban_phone_n_7d1a63_idx'), models.Index(fields=['transaction_reference'], name='wallets_ban_transac_01c6b7_idx')],
            },
        ),
    ]
