# Generated by Django 5.2.6 on 2025-12-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0007_alter_processedtransaction_user_bancabcapilog'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancabcapilog',
            name='auto_credit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bancabcapilog',
            name='points_awarded',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
